language: ruby
rvm:
 - 2.7.1
gemfile:
 - Gemfile
before_install:
 - nvm install
install:
 - bundle install
 - npm install
script:
 - bundle exec htmlproofer ./
 - 
notifications:
  webhooks: https://coveralls.io/webhook