language: ruby
rvm:
 - 2.7.1
gemfile:
 - Gemfile
env:
 - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
 - nvm install
install:
 - bundle install
 - npm --prefix ./ci install
script:
 - bundle exec htmlproofer ./
 - npm --prefix ./ci test
notifications:
  webhooks: https://coveralls.io/webhook