language: ruby
rvm:
 - 2.7.1
gemfile:
 - ci/Gemfile
env:
 - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
 - nvm install
install:
 - bundle install
 - npm --prefix ./ci install
script:
 - bundle exec htmlproofer ../  --file-ignore '/node_modules/'
 - npm --prefix ./ci run test:coveralls
after_success: npm --prefix ./ci run test:coveralls:post
notifications:
  webhooks:
    urls:
      - https://coveralls.io/webhook
      - https://webhooks.gitter.im/e/b14bb9442f767070b059